# Generated by Django 3.0.3 on 2020-04-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.CharField(max_length=30)),
                ('customer_lname', models.CharField(max_length=30)),
                ('customer_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=30)),
                ('meal_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('meal_image', models.ImageField(upload_to='uploads/')),
                ('meal_availability_status', models.CharField(choices=[('unavailable', 'available'), ('available', 'available')], default='available', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=30)),
                ('payment_date', models.CharField(max_length=30)),
                ('payment_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_system.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30)),
                ('order_decription', models.CharField(max_length=200)),
                ('order_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_system.Customer')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_system.Menu')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_system.Payment')),
            ],
        ),
    ]
