# Generated by Django 3.0.3 on 2020-04-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_decription',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment',
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_system.Orders')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_system.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='MenueOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_system.Menu')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_system.Orders')),
            ],
        ),
    ]
