# Generated by Django 3.0.3 on 2020-04-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0002_auto_20200415_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='user_id',
        ),
    ]
