# Generated by Django 3.0.3 on 2020-04-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0003_auto_20200415_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menueorder',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='menueorder',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paymentorder',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='paymentorder',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
