# Generated by Django 3.0.3 on 2020-04-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0005_auto_20200416_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='menu',
        ),
        migrations.AddField(
            model_name='orders',
            name='menu',
            field=models.ManyToManyField(to='restaurant_system.Menu'),
        ),
        migrations.DeleteModel(
            name='MenueOrder',
        ),
    ]
