# Generated by Django 3.0.3 on 2020-04-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0006_auto_20200416_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='order',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
