# Generated by Django 3.0.3 on 2020-04-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0008_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal_availability_status',
            field=models.CharField(choices=[('unavailable', 'unavailable'), ('available', 'available')], default='available', max_length=255),
        ),
    ]
