# Generated by Django 3.0.3 on 2020-04-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0009_auto_20200418_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
