# Generated by Django 3.0.3 on 2020-05-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0011_orders_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentOrder',
        ),
    ]
