# Generated by Django 3.0.3 on 2020-05-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0013_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_status',
        ),
    ]
