# Generated by Django 3.0.3 on 2020-05-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0014_remove_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('draft', 'draft'), ('confirmed', 'confirmed'), ('declined', 'declined')], default='draft', max_length=255),
        ),
    ]
