# Generated by Django 3.0.3 on 2020-05-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0015_orders_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
