# Generated by Django 3.0.3 on 2020-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0017_orders_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meal_category',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('drinks', 'drinks')], default='lunch', max_length=30),
        ),
    ]
